### PR TITLE
Prepare for -sys release 0.5.0

### PR DESCRIPTION
**Pull request by jonasnick**
I messed up #41 by forgetting to also bump -sys.

### CODE REVIEW

**Comment by jonasnick** [comment]
Fwiw I also tried to update the vendored secp-zkp library, but that results in test failure which under valgrind shows that something is going very wrong memory wise and valgrind is pointing to something being wrong with the context. My hypothesis is that the preallocated context size changed in secp-zkp, but since we're reusing the `Context` from rust-secp, which is behind in C-libsecp the `Context` doesn't have the updated preallocated context size.

**Comment by Tibo-lg** [comment]
Just trying to be useful, but I can confirm that tests fail with latest secp-zkp. And I get the exact same result using the previously used commit (f3708a1ecb445b1b05a0f8fcd1da6a88f83d89c4).

**Comment by apoelstra** [comment]
We can update the library in rust-secp to match rust-secp-zkp since we are about to do a major release anyway.

@jonasnick suggested to me in another channel that he was working on this, so I'll leave that to him.

**Comment by thomaseizinger** [comment]
@jonasnick Any chance we can get a release out without the changes to the vendored C library? I would like to get rid of Git dependencies :)

**Review by jonasnick — COMMENTED** [review]
In order to get a release out we need to merge this PR, but no one approved it so far.

**Review by Tibo-lg — APPROVED** [review]
ack cdba7dc7dd83200f44fc301f3de86c9fe9a6b4e9

**Pull request merged**
