### PR TITLE
bump version to 0.7 and update CHANGELOG

### PR DESCRIPTION
**Pull request by RCasatta**

### CODE REVIEW

**Review by apoelstra — APPROVED** [review]
ACK 6c91269ccdfa8c3fa02659d2dde1262df48127c7

**Comment by apoelstra** [comment]
cc @jonasnick should we do a release?

**Review by jonasnick — COMMENTED** [review]
I think we also have to bump secp256k1-zkp-sys. Otherwise version 0.7.0 of secp256k1-zkp will pull in version 0.6.0 of secp256k1-zkp-sys which is incompatible due to #56.

**Comment by RCasatta** [comment]
I used `./vendor-libsecp.sh depend 0_7_0 d22774e248c703a191049b78f8d04f37d6fcfa05` to create ba2fecb03cbcb8cef8b2f6cbe19a7b692026d280
where d22774e248c703a191049b78f8d04f37d6fcfa05 is current secp256k1-zkp master

I had to fix a patch file in 09102ffebd87d18e184e18ea16d20ea7b6ba4f65 otherwise it didn't apply correcty

**Review by apoelstra — APPROVED** [review]
ACK ba2fecb03cbcb8cef8b2f6cbe19a7b692026d280

**Review by jonasnick — COMMENTED** [review]
~~ACK ba2fecb03cbcb8cef8b2f6cbe19a7b692026d280~~

**Comment by jonasnick** [comment]
Sorry I had to take back my ACK. It seems like you didn't update secp-zkp-sys to 0.7.0.

**Comment by RCasatta** [comment]
Sorry, thanks for spotting.

**Review by jonasnick — COMMENTED** [review]
It's neither obvious nor documented how to update rust-secp256k1-zkp. So, it's easy to make this mistake (which I have done before as well). 

ACK 32ed375307fddc72b808df7867589592fa9eb024

**Comment by jonasnick** [comment]
Published both libs to crates.io.

**Pull request merged**
