### PR TITLE
Prepare for minor release 0.3.0

### PR DESCRIPTION
**Pull request by jonasnick**

### CODE REVIEW

**Review by thomaseizinger — APPROVED** [review]
I guess even if there aren't any obvious breaking changes, it is better to err on the safe side of bumping the minor version instead of patch.

**Comment by jonasnick** [comment]
As @sanket1729 pointed out to me, for some (rather esoteric afaics) matching on the Error type this can be a breaking change.

**Comment by thomaseizinger** [comment]
> As @sanket1729 pointed out to me, for some (rather esoteric afaics) matching on the Error type this can be a breaking change.

Not very esoteric actually. An exhaustive `match` (ie not using `_ => {}`)  will fail to compile once a variant is added.

**Comment by jonasnick** [comment]
Published on crates.io. @Tibo-lg fyi in case you want to use the crates.io release for ECDSA adaptor sigs.

**Comment by Tibo-lg** [comment]
Thanks for the notice I do want to use it :)

**Pull request merged**
