### PR TITLE
Add derives for surjectionproofs

### PR DESCRIPTION
**Pull request by sanket1729**

### CODE REVIEW

**Comment by thomaseizinger** [comment]
That doesn't work on 1.29 unfortunately :(

We will need a fairly recent rustc for this because it requires min-const-generics AFAIK.

**Comment by sanket1729** [comment]
Is there any strong reason to not do a simple manual implementation for these traits?

**Comment by thomaseizinger** [comment]
> Is there any strong reason to not do a simple manual implementation for these traits?

As in, loop through the array and check each element?

For an 8000 element array, this might be expensive although I haven't conducted any experiments. Happy to merge a manual implementation if you need these traits!

**Comment by sanket1729** [comment]
Moved to #16

**Pull request closed without merging**
