### PR TITLE
Fix Pedersen Commitment deserialization

### PR DESCRIPTION
**Pull request by luckysori**
The first commit identifies the bug and the second fixes it. If this PR gets approved I'll squash them together.

### CODE REVIEW

**Review by jonasnick — COMMENTED** [review]
Looks good to me. Not sure what's wrong with CI.

**Review by thomaseizinger — APPROVED** [review]
Interesting, what a stupid copy-paste bug :D

I have two concerns:

1. If you want to test the serialization, can we test it using `serde_test` please AND make sure we cover the human-readable / non-human-readable part as well?
2. Given that the bug occurred within the `str::FromStr` implementation, I would actually prefer if we test that instead of the `serde` impl which just happened to forward to that. That would also be good because it ensures that we are actually upholding the invariant of `Display`/`FromStr` being round-trippable.

Happy to merge this if it is urgent, as long as there is a follow-up!

**Review by thomaseizinger — APPROVED** [review]

**Comment by thomaseizinger** [comment]
Thanks for updating the tests!

**Comment by thomaseizinger** [comment]
@jonasnick I merged this based on the assumption that https://github.com/ElementsProject/rust-secp256k1-zkp/pull/10#pullrequestreview-626109161 is an ACK :)

**Comment by jonasnick** [comment]
@thomaseizinger yup all good, my comment was more like "one real ACK is fine for this"

**Pull request merged**
