### PR TITLE
Errors are swallowed in CI

### PR DESCRIPTION
**Pull request by rishflab**
This branch is fails intentionally on the `wasm-pack build` step. The error is swallowed in CI and it shows green.

#26

### CODE REVIEW

**Review by jonasnick — COMMENTED** [review]
This is normal bash behavior. You can test this with
```
#!/bin/sh  -e
false && true
echo "foo"
```

I think you can just remove `&&`.

**Comment by rishflab** [comment]
> This is normal bash behavior. You can test this with
> 
> ```
> #!/bin/sh  -e
> false && true
> echo "foo"
> ```
> 
> I think you can just remove `&&`.

ahhh
thanks!

**Comment by jonasnick** [comment]
Looks good to me. Needs rebase and undrafting.

**Review by jonasnick — APPROVED** [review]
ACK 9a31a51f07aac2198b02e2c4aed2fe1b9d1c8d7f

**Pull request merged**
